### ISSUE TITLE
Stone stairway cannot be build in some cases

### ISSUE THREAD

**Issue by Makishima** [WarpzoneStudios/Hammerting#61] opened 2021-02-20 15:06 UTC
I can build a stairway under stone bridge
![изображение](https://user-images.githubusercontent.com/5548003/108600117-3c65c500-73a6-11eb-8149-9b6ad7a4a0ba.png)
But cannot place it under it
![изображение](https://user-images.githubusercontent.com/5548003/108600122-4687c380-73a6-11eb-8047-a29fcfbb6ecd.png)

**Comment by Srekel** [comment] 2021-02-24 07:24
Duplicate of #60

**Closed by Srekel** 2021-02-24 07:24 UTC
